"""Add stage order to document tracking

Revision ID: dcb8a0daf83e
Revises: 1a4573dde82f
Create Date: 2026-06-28 18:53:56.717445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb8a0daf83e'
down_revision = '1a4573dde82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "stage_order",
                sa.Integer(),
                nullable=False,
                server_default="0"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('stage_order')

    # ### end Alembic commands ###
